CREATE TABLE 'maks1' (
    'Id' INT(11) NOT NULL AUTO_INCREMENT ,
    'Name' VARCHAR(255) NOT NULL , 
    PRIMARY KEY ('Id')
    ) 
ENGINE = InnoDB;

CREATE TABLE 'maks2' (
    'Id' INT(11) NOT NULL AUTO_INCREMENT ,
    'Name' VARCHAR(255) NOT NULL , 
    PRIMARY KEY ('Id')
    ) 
ENGINE = InnoDB;